# Generated by Django 4.2.11 on 2024-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
        migrations.AddField(
            model_name="profile",
            name="fatPercentage",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pushUpNumbers",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="tall",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="weight",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
