# Generated by Django 4.2.11 on 2024-05-07 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_city_profile_fatpercentage_profile_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="blankDuratin",
            new_name="blankDuration",
        ),
    ]
