# Generated by Django 4.2.11 on 2024-05-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="blankDuration",
            field=models.DurationField(),
        ),
    ]
