# Generated by Django 4.2.11 on 2024-05-12 02:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="duration_field",
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
