# Generated by Django 4.2.11 on 2024-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0002_program_created_by_program_duration_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="day",
            new_name="days",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="image",
            field=models.ImageField(upload_to="exercise/"),
        ),
        migrations.AlterField(
            model_name="program",
            name="feedback",
            field=models.IntegerField(
                choices=[
                    (1, "Foolproof"),
                    (2, "Easy"),
                    (3, "Normal"),
                    (4, "Difficult"),
                    (5, "Fiendish"),
                ]
            ),
        ),
    ]
