# Generated by Django 4.2.11 on 2024-05-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0003_rename_day_exercise_days_alter_exercise_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Muscle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="muscle/")),
                ("level", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="practice",
            old_name="exerxise",
            new_name="exercise",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="level",
        ),
        migrations.RemoveField(
            model_name="program",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="program",
            name="level",
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercise.muscle",
            ),
            preserve_default=False,
        ),
    ]
